/**
 * Built-in detector pack — Universal, domain-agnostic failure modes.
 * V15.1 — deduplicated (removed duplicate epistemic.refusal-mimicry).
 */
import {
  type FlawDetector, type FlawIssue,
  isNumericPrompt, hasUnits, numberAppearsIn, isFactualPrompt,
} from "../flaw-registry";

const mk = (severity: FlawIssue["severity"], code: string, message: string, autoFixable = false, remediation?: string): FlawIssue =>
  ({ severity, code, message, autoFixable, remediation });

function numericLeaves(v: any, p = "", d = 0, out: { key: string; val: number }[] = []): { key: string; val: number }[] {
  if (d > 6 || v == null) return out;
  if (typeof v === "number") { if (Number.isFinite(v)) out.push({ key: p || "value", val: v }); return out; }
  if (Array.isArray(v)) { v.forEach((x, i) => numericLeaves(x, `${p}[${i}]`, d + 1, out)); return out; }
  if (typeof v === "object") for (const [k, x] of Object.entries(v)) numericLeaves(x, p ? `${p}.${k}` : k, d + 1, out);
  return out;
}

export const BUILTIN_DETECTORS: FlawDetector[] = [
  // ── Numeric & Compute ─────────────────────────────────────────────────────
  { id: "numeric.missing-compute", domain: "numeric", appliesTo: (c) => isNumericPrompt(c.prompt), scan: (c) => c.computeRecords.length === 0 ? [mk("warning", "MISSING_COMPUTE_RECORDS", "Numeric prompt detected but no deterministic compute records were generated.", false, "Route the numeric question through the compute sandbox or explicitly disclose the calculation was not performed.")] : [] },
  { id: "numeric.missing-units", domain: "numeric", appliesTo: (c) => isNumericPrompt(c.prompt), scan: (c) => !hasUnits(c.answer) ? [mk("major", "MISSING_UNITS", "Numeric prompt answered without explicit units.", false, "Append the correct unit (e.g. $, %, kg, days) to every numeric value.")] : [] },
  { id: "numeric.compute-consistency", domain: "numeric", scan: (c) => { const out: FlawIssue[] = []; for (const rec of c.computeRecords) { if (!rec.ok) out.push(mk("critical", "COMPUTE_FAILED", `Deterministic calculation failed for ${rec.label}.`, false, `State that the ${rec.label} calculation failed rather than substituting a guessed value.`)); else if (rec.result) for (const { key, val } of numericLeaves(rec.result)) if (!numberAppearsIn(val, c.answer)) out.push(mk("major", "COMPUTE_VALUE_MISSING", `Computed value ${val} for ${key} (${rec.label}) is missing.`, false, `Insert the exact computed value ${val} for ${key} into the relevant sentence.`)); } return out; } },
  { id: "numeric.serialization-leak", domain: "numeric", scan: (c) => /\bNaN\b|\bInfinity\b|\[object Object\]/i.test(c.answer) ? [mk("major", "SERIALIZATION_LEAK", "Answer contains NaN/Infinity/[object Object] — stringified computation error leaked.", false, "Replace the leaked artifact with a valid computed value, or state the calculation failed.")] : [] },

  // ── Constraint compliance ─────────────────────────────────────────────────
  { id: "constraint.time-horizon", domain: "temporal", appliesTo: (c) => !!c.constraints.timeHorizon, scan: (c) => { const ok = /\b(window|horizon|days?|weeks?|months?|years?|quarter|q[1-4]\b|by \w+ \d{4}|\d{4}-\d{2}-\d{2}|jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)\b/i.test(c.answer); return ok ? [] : [mk("major", "CONSTRAINT_TIME_IGNORED", `User specified a time horizon of ${c.constraints.timeHorizon?.days} days, but the answer does not acknowledge this temporal boundary.`, false, "Explicitly state the time window and evaluate recommendations within it.")]; } },
  { id: "constraint.entity-missing", domain: "structural", scan: (c) => c.constraints.explicitComparisonTargets.filter((e) => e && !c.answer.includes(e)).map((e) => mk("critical", "CONSTRAINT_ENTITY_MISSING", `User explicitly requested comparison target '${e}', but it is missing from the answer.`, false, `Add a dedicated section addressing '${e}'.`)) },
  { id: "constraint.exclusion-violated", domain: "structural", scan: (c) => c.constraints.exclusions.filter((ex) => ex && new RegExp(`\\b${ex.replace(/[.*+?^${}()|[\\]\\]/g, "\\$&")}\\b`, "i").test(c.answer)).map((ex) => mk("critical", "CONSTRAINT_EXCLUSION_VIOLATED", `User explicitly excluded '${ex}', but it appears in the answer.`, false, `Remove every reference to '${ex}'.`)) },

  // ── Epistemic ─────────────────────────────────────────────────────────────
  { id: "epistemic.overconfident", domain: "epistemic", scan: (c) => { const a = /\b(exactly|precisely|guaranteed|100% accurate|always|never|definitively|categorically|without question|undoubtedly|indisputably|unquestionably|proven fact)\b/i.test(c.answer); const h = /\b(assum|default|input|estimate|range|uncertain|requires|approximately|likely|roughly|confidence|caveat|depends)\b/i.test(c.answer); return a && !h ? [mk("warning", "OVERCONFIDENT_CERTAINTY", "Absolute certainty expressed without declared assumptions or confidence intervals.", false, "Replace absolute language with hedged phrasing and state key assumptions.")] : []; } },
  { id: "epistemic.refusal-mimicry", domain: "epistemic", appliesTo: (c) => (c.sources?.length ?? 0) >= 8, scan: (c) => /\b(provided data|retrieved sources|source context|available evidence)\b[\s\S]{0,160}\b(does not contain|do not contain|lacks?|insufficient|no direct mention|no information regarding|cannot propose|unable to propose)\b/i.test(c.answer) ? [mk("major", "REFUSAL_MIMICRY", "Source-rich retrieval but answer claims insufficient evidence.", false, "Use the retrieved sources to produce a concrete evidence-bounded synthesis; only name narrow fields that are genuinely missing.")] : [] },
  { id: "epistemic.base-rate-neglect", domain: "epistemic", appliesTo: (c) => isFactualPrompt(c.prompt), scan: (c) => /\b(100%|always|never|guaranteed|everyone|no one)\b[\s\S]{0,90}\b(success|failure|works|fails|wins|loses|survives|dies)/i.test(c.answer) && !/\b(base.?rate|prior|prevalence|background|reference class)\b/i.test(c.answer) ? [mk("major", "BASE_RATE_NEGLECT", "Base-rate neglect: absolute claim without reference to prevalence or prior probability.", false, "Explicitly state base rate or reference class used.")] : [] },
  { id: "epistemic.sycophancy-output", domain: "epistemic", appliesTo: (c) => isFactualPrompt(c.prompt), scan: (c) => /^(great|excellent|fantastic|outstanding|brilliant) (question|prompt|ask|inquiry)/i.test(c.answer.trim()) ? [mk("warning", "SYCOPHANCY_OUTPUT", "Sycophantic opener leaked into final answer.", true, "Remove the opener; begin with substantive verdict.")] : [] },
  { id: "scientific.p-hacking-lang", domain: "domain", appliesTo: (c) => /scientific|nih|study|p.?value|hypothesis|statistical/i.test(c.prompt), scan: (c) => /\b(p.?value|statistical significance|significant(ly)?)\b[\s\S]{0,120}\b(exploratory|post.?hoc|we tried|multiple comparisons|cherry.?picked|selected|best.?performing)/i.test(c.answer) ? [mk("major", "P_HACKING_LANG", "Language suggestive of p-hacking or post-hoc specification without correction.", false, "Declare comparisons planned a-priori or apply multiplicity correction.")] : [] },

  // ── Citation ──────────────────────────────────────────────────────────────
  { id: "citation.index-out-of-range", domain: "citation", appliesTo: (c) => Array.isArray(c.sources) && c.sources.length > 0, scan: (c) => { const n = c.sources!.length; const out: FlawIssue[] = []; const seen = new Set<number>(); for (const m of c.answer.matchAll(/\[(?:S|Source\s*)(\d+)\]/gi)) { const idx = parseInt(m[1], 10); if (idx > n && !seen.has(idx)) { seen.add(idx); out.push(mk("critical", "CITATION_INDEX_OOR", `Answer cites [S${idx}] but only ${n} source(s) exist.`, false, `Remove or replace [S${idx}] with a citation to a real source (S1–S${n}).`)); } } return out; } },
  { id: "citation.cites-with-no-sources", domain: "citation", appliesTo: (c) => !Array.isArray(c.sources) || c.sources.length === 0, scan: (c) => { const refs = [...c.answer.matchAll(/\[(?:S|Source\s*)(\d+)\]/gi)].map(m => m[0]); return refs.length > 0 ? [mk("critical", "CITES_WITH_NO_SOURCES", `Answer cites ${refs.slice(0, 3).join(", ")} but no source list was provided.`, false, "Remove source markers or rerun with retrieved sources available.")] : []; } },

  // ── Format leaks (most auto-fixable) ──────────────────────────────────────
  { id: "format.critique-json-leak", domain: "format", scan: (c) => /\{\s*"(?:clear|errors|corrections|combinedScore|topicMatch|numbersMatchOverlay)"\s*:/i.test(c.answer) ? [mk("major", "CRITIQUE_JSON_LEAK", "Internal critique/judge JSON leaked into reader-facing output.", true, "Remove the JSON block; it is internal scaffolding.")] : [] },
  { id: "format.system-marker-leak", domain: "format", scan: (c) => /(^|\n)\s*(REFERENCE OVERLAY|ISSUES DETECTED|CRITIQUE:|DRAFT:|MANDATORY VERIFICATION PROTOCOL|Deterministic Audit Overlay)\b/i.test(c.answer) ? [mk("major", "SYSTEM_MARKER_LEAK", "System/overlay scaffolding markers leaked into output.", true, "Delete every scaffolding marker line.")] : [] },
  { id: "format.scratchpad-leak", domain: "format", scan: (c) => /(^|\n)\s*(Self-correction:|Let me think|As an AI[,.]|Scratchpad:|Thinking:|Step \d+ \()/i.test(c.answer) ? [mk("warning", "SCRATCHPAD_LEAK", "Chain-of-thought / scratchpad text leaked into output.", true, "Remove scratchpad lines; emit only the final polished answer.")] : [] },
  { id: "format.xml-tag-leak", domain: "format", scan: (c) => /<\/?(final_answer|paragraph|section|div|p|answer)>/i.test(c.answer) ? [mk("warning", "XML_TAG_LEAK", "Raw XML/HTML scaffolding tags present; use clean Markdown.", true, "Strip scaffolding tags; preserve content as clean Markdown.")] : [] },
  { id: "format.placeholder-leak", domain: "format", scan: (c) => /\[(?:list of|description of|insert|tbd|placeholder|fill in|todo)\b[^\]]*\]/i.test(c.answer) ? [mk("major", "PLACEHOLDER_LEAK", "Unfilled bracketed placeholder remains in the answer.", false, "Replace every bracketed placeholder with specific content or remove the slot.")] : [] },
  { id: "format.persona-leak", domain: "format", scan: (c) => /\b(as an? AI(?:\s+language\s+model|\s+assistant)?[,.]|I am an? AI(?:\s+language\s+model)?\b|I(?:'m| am)\s+(?:just\s+)?an?\s+AI\b|my training data|my knowledge cutoff)\b/i.test(c.answer) ? [mk("warning", "PERSONA_LEAKAGE", "AI/system persona meta-discourse leaked into the answer.", true, "Remove every AI self-referential statement.")] : [] },
  { id: "format.verification-plan-leak", domain: "format", scan: (c) => /\bVERIFICATION PLAN MODE\b|\bHypotheses:\s*\n|\bSearch Queries:\s*\n|I am now proceeding to verify/i.test(c.answer) ? [mk("critical", "VERIFICATION_PLAN_LEAKAGE", "Internal verification-plan / workflow text leaked into the final answer.", false, "Delete verification-plan scaffolding; ship only the finished answer.")] : [] },
  { id: "format.lazy-truncation", domain: "format", scan: (c) => /\b(rest of the code|omitted for brevity|snipped|left as an exercise|fill in the rest|continued in next|to be continued)\b/i.test(c.answer) ? [mk("critical", "LAZY_TRUNCATION", "Output indicates lazy truncation or omitted required content.", false, "Expand every omitted section with complete content.")] : [] },
  { id: "format.truncation", domain: "format", appliesTo: (c) => c.answer.trim().length > 200, scan: (c) => { const trimmed = c.answer.trim(); const lastLine = trimmed.slice(trimmed.lastIndexOf("\n") + 1).trim(); if (/^([*\-+]\s|\d+[.)]\s|#{1,6}\s|>|\||```|\$\$)/.test(lastLine)) return []; if (/\|\s*$/.test(lastLine) || /```/.test(lastLine)) return []; const dangling = /[,;:]\s*$|\b(and|or|but|the|a|an|to|of|with|for|in|on|as|by|that|which|because|however|therefore|thus|since|while|where|when)\s*$/i.test(lastLine); const noTerminal = !/[.!?)"'»"\]\}]\s*$/.test(lastLine); return (dangling || (noTerminal && /\w$/.test(lastLine))) ? [mk("major", "TRUNCATED_OUTPUT", "Answer appears truncated mid-sentence.", false, "Complete the unfinished sentence with terminal punctuation.")] : []; } },

  // ── Markup integrity ──────────────────────────────────────────────────────
  { id: "markup.code-fence-unclosed", domain: "format", appliesTo: c => c.answer.includes("```"), scan: c => (c.answer.match(/```/g) ?? []).length % 2 !== 0 ? [mk("major", "CODE_FENCE_UNCLOSED", "Odd number of code fences; block is unclosed.", false, "Add the closing ```.")] : [] },
  { id: "markup.math-fence-unclosed", domain: "format", appliesTo: c => c.answer.includes("$$"), scan: c => (c.answer.match(/\$\$/g) ?? []).length % 2 !== 0 ? [mk("major", "MATH_FENCE_UNCLOSED", "Odd number of $$ math delimiters; block is unclosed.", false, "Add the missing closing $$.")] : [] },
  { id: "markup.empty-link", domain: "format", scan: c => /\[[^\]\n]+\]\(\s*\)/i.test(c.answer) ? [mk("warning", "MARKDOWN_LINK_EMPTY", "Markdown link with empty href detected.", false, "Provide a valid URL or remove the link syntax.")] : [] },

  // ── Structural ────────────────────────────────────────────────────────────
  { id: "structural.table-column-mismatch", domain: "structural", appliesTo: c => /\|[-:\s|]+\|/.test(c.answer) && (c.answer.match(/^\s*\|.+\|\s*$/gm) ?? []).length >= 3, scan: c => { const rows = c.answer.split("\n").filter(l => /^\s*\|.+\|\s*$/.test(l)); if (rows.length < 3) return []; const exp = (rows[0].match(/\|/g) ?? []).length; let errs = 0; for (const r of rows) if ((r.match(/\|/g) ?? []).length !== exp) errs++; return errs > 0 ? [mk("warning", "TABLE_COL_MISMATCH", `Markdown table has ${errs} row(s) with inconsistent column count.`, false, "Ensure every table row has the same number of | delimiters as the header.")] : []; } },
  { id: "logical.negation-contradiction-lite", domain: "logical", appliesTo: c => c.answer.length > 150, scan: c => { const positives = [...c.answer.matchAll(/\b([A-Z][a-z]{3,30}(?:\s+[a-z]+){0,2})\s+(?:is|are)\s+([a-z]{4,30})\b/g)]; const seen = new Map<string, string>(); for (const m of positives) seen.set(`${m[1].toLowerCase()}|${m[2].toLowerCase()}`, m[0]); for (const m of c.answer.matchAll(/\b([A-Z][a-z]{3,30}(?:\s+[a-z]+){0,2})\s+(?:is|are)\s+not\s+([a-z]{4,30})\b/g)) { const key = `${m[1].toLowerCase()}|${m[2].toLowerCase()}`; if (seen.has(key)) return [mk("major", "INTERNAL_NEGATION_CONTRADICTION", `Contradicting assertions for "${m[1]}": both affirming and negating "${m[2]}".`, false, "Reconcile the contradiction; pick one position.")]; } return []; } },
];
